name: BuniBot CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "14.x"

jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: es-lint
        run: npm run lint

